### ISSUE TITLE
RSI strategy 

### ISSUE THREAD

**Issue by 517-dot** [mick-liu/tagenalgo#2]
Usually we define buying and selling RSI strategy as 20 and 80, what are the reasons for using 30 and 70 here?

**Comment by mick-liu** [comment]
Good question! What you asked is totally the problem we want to solve by implementing Tagenalgo. In practice, traders usually modify the parameters set for different markets with same strategy due to the variety of volatility in different markets.

For example, in the high volatility markets such as foreign exchanges or cryptocurrency market, traders might set a wider range for the low and up threshold such as 20 and 80, because the price movement might maintain the same direction when the RSI value reaches 30 or 70. If so, we cannot expect to earn with the mean-reversion strategy. On the other hand, in stock market, 30 and 70 for buying and selling might be better, because the price will immediately reverse when the RSI value cross over our thresholds setting. 

Though the logic sounds reasonable, we still do not know if the parameters set such as (30, 70) or (20, 80) can bring us the most profits. Therefore, we can use the genetic algorithm to find out the best local parameters set for the strategy.

**Comment by mick-liu** [comment]
> 
> 
> Usually we define buying and selling RSI strategy as 20 and 80, what are the reasons for using 30 and 70 here?

Good question! What you asked is totally the problem we want to solve by implementing Tagenalgo. In practice, traders usually modify the parameters set for different markets with same strategy due to the variety of volatility in different markets.

For example, in the high volatility markets such Forex futures or cryptocurrency market, traders might set a wider range for the low and up threshold such as 20 and 80, because the price movement might maintain the same direction when the RSI value reaches 30 or 70. If so, we cannot expect to earn with the mean-reversion strategy. On the other hand, in stock market, 30 and 70 for buying and selling might be better, because the price will immediately reverse when the RSI value cross over our thresholds setting.

Though the logic sounds reasonable, we still do not know if the parameters set such as (30, 70) or (20, 80) can bring us the most profits. Therefore, we can use the genetic algorithm to find out the best local parameters set for the strategy.

**Comment by 517-dot** [comment]
> > Usually we define buying and selling RSI strategy as 20 and 80, what are the reasons for using 30 and 70 here?
> 
> Good question! What you asked is totally the problem we want to solve by implementing Tagenalgo. In practice, traders usually modify the parameters set for different markets with same strategy due to the variety of volatility in different markets.
> 
> For example, in the high volatility markets such as foreign exchanges or cryptocurrency market, traders might set a wider range for the low and up threshold such as 20 and 80, because the price movement might maintain the same direction when the RSI value reaches 30 or 70. If so, we cannot expect to earn with the mean-reversion strategy. On the other hand, in stock market, 30 and 70 for buying and selling might be better, because the price will immediately reverse when the RSI value cross over our thresholds setting.
> 
> Though the logic sounds reasonable, we still do not know if the parameters set such as (30, 70) or (20, 80) can bring us the most profits. Therefore, we can use the genetic algorithm to find out the best local parameters set for the strategy.
